MISSING_LABEL_ID_TITLE = "MISSING_LABEL"
MISSING_LABEL_LOG_MESSAGE = "label was None when trying to fetch Git labels"

MISSING_USER_ID_LOG_MESSAGE = "user_id was None when trying to fetch Git labels"
MISSING_USER_ID_TITLE = "MISSING_USER_ID"

LABEL_ALREADY_EXISTS_TITLE = "GIT_LABEL_ALREADY_EXISTS"
LABEL_ALREADY_EXISTS_MESSAGE = "Git Label Already Exists"

REPOSITORY_DOESNT_EXIST_TITLE = "REPO_NOT_EXIST"
REPOSITORY_DOESNT_EXIST_MESSAGE = "Repository doesn't exist"

REPO_ALREADY_EXISTS_TITLE = "REPO_ALREADY_EXISTS"
REPO_ALREADY_EXISTS_MESSAGE = "Repo Already Exists"